Update lib.pyx
following the issue raised due to the error message:

Traceback (most recent call last):
  File "tutorial-part1.py", line 18, in <module>
    u, v = openpiv.filters.replace_outliers( u, v, method='localmean', max_iter=10, kernel_size=2)
  File "/usr/local/lib/python2.7/dist-packages/openpiv/filters.py", line 122, in replace_outliers
    u = replace_nans( u, method=method, max_iter=max_iter, tol=tol, kernel_size=kernel_size )
  File "lib.pyx", line 61, in openpiv.lib.replace_nans (openpiv/src/lib.c:1890)
ValueError: Buffer dtype mismatch, expected 'DTYPEi_t' but got 'int'

It seems that we shall leave it as 'int' without specifying the 32 vs 64 bit