fixed the bug of nonzero returning int64 on 64bit
np.nonzero returns int64 on 64 bit machines and it causes a bug: 

ValueError: Buffer dtype mismatch, expected 'DTYPEi_t' but got 'long long'

fixed it using the list comprehension and conversion of a tuple to DTYPEi